def connect_main_window_signals(self) -> None:
    self.import_button.clicked.connect(self.choose_pdf)
    self.batch_import_button.clicked.connect(self.choose_pdfs)
    self.remove_pdf_button.clicked.connect(self.remove_current_pdf)
    self.parse_button.clicked.connect(self.parse_pdfs)
    self.choose_archive_button.clicked.connect(self.choose_archive_root)
    self.open_archive_button.clicked.connect(self.open_archive_root)
    self.open_paper_folder_button.clicked.connect(self.load_archived_paper_folder)
    self.archive_stats_button.clicked.connect(self.show_archive_stats)
    self.validate_key_button.clicked.connect(self.validate_api_key)
    self.save_key_button.clicked.connect(self.save_api_key)
    self.provider_combo.currentIndexChanged.connect(self.apply_provider_preset)
    self.prev_paper_button.clicked.connect(lambda: self.move_paper(-1))
    self.next_paper_button.clicked.connect(lambda: self.move_paper(1))
    self.save_info_button.clicked.connect(self.save_current_info)
    self.save_note_button.clicked.connect(self.save_note)
    self.show_json_button.clicked.connect(self.show_current_json)
    self.show_prompt_button.clicked.connect(self.show_current_prompt)
    self.scholar_button.clicked.connect(self.open_google_scholar)
    self.journal_use_current_button.clicked.connect(self.use_current_journal)
    self.journal_search_button.clicked.connect(self.lookup_journal)
    self.journal_open_button.clicked.connect(self.open_journal_source)
    self.archive_papers_refresh_button.clicked.connect(self.load_archive_papers_table)
    self.archive_papers_organize_button.clicked.connect(self.organize_archive_papers)
    self.archive_papers_open_button.clicked.connect(self.open_selected_archive_paper)
    self.archive_search_edit.textChanged.connect(self.load_archive_papers_table)
    self.archive_tag_filter_combo.currentIndexChanged.connect(self.load_archive_papers_table)
    self.archive_filter_clear_button.clicked.connect(self.clear_archive_filters)
    self.archive_all_tags_list.itemClicked.connect(self.on_archive_tag_clicked)
    self.archive_tag_rename_button.clicked.connect(self.rename_selected_archive_tag)
    self.archive_tag_merge_button.clicked.connect(self.merge_archive_same_name_tags)
    self.archive_papers_table.cellDoubleClicked.connect(
        lambda _row, _column: self.open_selected_archive_paper()
    )
